# frozen_string_literal: true

# Standard libraries.
# rubocop:disable Lint/RedundantRequireStatement
require "English"
require "cgi"
require "date"
require "erb"
require "etc"
require "json"
require "net/http"
require "pathname"
require "rbconfig"
require "securerandom"
require "set"
require "stringio"
require "time"
require "uri"
# rubocop:enable Lint/RedundantRequireStatement

# We already ship the preferred sorbet manifests in the package itself.
# `tapioca` currently does not offer us a way to opt out of unnecessary compilation.
if Object.const_defined?(:Tapioca) && caller.chain([$PROGRAM_NAME]).chain(ARGV).grep(/tapioca/)
  return
end

# Gems.
require "connection_pool"

# Package files.
require_relative "packages/version"
require_relative "packages/internal/util"
require_relative "packages/internal/type/converter"
require_relative "packages/internal/type/unknown"
require_relative "packages/internal/type/boolean"
require_relative "packages/internal/type/file_input"
require_relative "packages/internal/type/enum"
require_relative "packages/internal/type/union"
require_relative "packages/internal/type/array_of"
require_relative "packages/internal/type/hash_of"
require_relative "packages/internal/type/base_model"
require_relative "packages/internal/type/base_page"
require_relative "packages/internal/type/request_parameters"
require_relative "packages/internal"
require_relative "packages/request_options"
require_relative "packages/file_part"
require_relative "packages/errors"
require_relative "packages/internal/transport/base_client"
require_relative "packages/internal/transport/pooled_net_requester"
require_relative "packages/client"
require_relative "packages/models/registries/package"
require_relative "packages/models/dependency"
require_relative "packages/models/dependency_list_params"
require_relative "packages/models/dependency_list_response"
require_relative "packages/models/keyword"
require_relative "packages/models/keyword_list_params"
require_relative "packages/models/keyword_list_response"
require_relative "packages/models/keyword_retrieve_params"
require_relative "packages/models/keyword_retrieve_response"
require_relative "packages/models/package_lookup_params"
require_relative "packages/models/package_lookup_response"
require_relative "packages/models/package_with_registry"
require_relative "packages/models/registries/maintainer"
require_relative "packages/models/registries/maintainer_list_packages_params"
require_relative "packages/models/registries/maintainer_list_packages_response"
require_relative "packages/models/registries/maintainer_list_params"
require_relative "packages/models/registries/maintainer_list_response"
require_relative "packages/models/registries/maintainer_retrieve_params"
require_relative "packages/models/registries/namespace"
require_relative "packages/models/registries/namespace_list_packages_params"
require_relative "packages/models/registries/namespace_list_packages_response"
require_relative "packages/models/registries/namespace_list_params"
require_relative "packages/models/registries/namespace_list_response"
require_relative "packages/models/registries/namespace_retrieve_params"
require_relative "packages/models/registries/package_list_dependent_package_kinds_params"
require_relative "packages/models/registries/package_list_dependent_package_kinds_response"
require_relative "packages/models/registries/package_list_dependent_packages_params"
require_relative "packages/models/registries/package_list_dependent_packages_response"
require_relative "packages/models/registries/package_list_params"
require_relative "packages/models/registries/package_list_related_packages_params"
require_relative "packages/models/registries/package_list_related_packages_response"
require_relative "packages/models/registries/package_list_response"
require_relative "packages/models/registries/package_list_version_numbers_params"
require_relative "packages/models/registries/package_list_version_numbers_response"
require_relative "packages/models/registries/package_retrieve_params"
require_relative "packages/models/registries/packages/version_list_params"
require_relative "packages/models/registries/packages/version_list_response"
require_relative "packages/models/registries/packages/version_retrieve_params"
require_relative "packages/models/registries/packages/version_retrieve_response"
require_relative "packages/models/registry"
require_relative "packages/models/registry_list_package_names_params"
require_relative "packages/models/registry_list_package_names_response"
require_relative "packages/models/registry_list_params"
require_relative "packages/models/registry_list_recent_versions_params"
require_relative "packages/models/registry_list_recent_versions_response"
require_relative "packages/models/registry_list_response"
require_relative "packages/models/registry_lookup_package_params"
require_relative "packages/models/registry_lookup_package_response"
require_relative "packages/models/registry_retrieve_params"
require_relative "packages/models"
require_relative "packages/resources/dependencies"
require_relative "packages/resources/keywords"
require_relative "packages/resources/packages"
require_relative "packages/resources/registries"
require_relative "packages/resources/registries/maintainers"
require_relative "packages/resources/registries/namespaces"
require_relative "packages/resources/registries/packages"
require_relative "packages/resources/registries/packages/versions"
